### ISSUE TITLE
セッション管理の方法

### ISSUE THREAD

**Issue by Techondorius** [tokyo-azisai-paradise/poker-mahjong-calculation#15]
@Hasegawa-Akito 
@Techondorius 

セッションの管理ってどうしますか？
タブを誤って閉じてしまった時とかに復帰したい時ってあると思うんですけどそういう時の復帰方法ってどうしましょうか？

**Comment by haseaki-poip** [comment]
frontとbackを完全に分離してるから、session管理はnext-sessionを使うかな

**Comment by Techondorius** [comment]
Cookie使う感じですかね？
承知しました。
